### ISSUE TITLE
Problems when the nomination page is different from the file name

### ISSUE THREAD

**Issue by Zitrax** [Zitrax/FPCBot#1]
The bot has some problems when the nomination page is different from the file name, the links becomes messed up after the results are confirmed, I had to fix them manually in the pages edited by the bot. I am not sure how to fix this problem, probably by adding a parameter the file nomination template when the filename is different from the nomination page? --Banzoo (talk) 21:39, 15 June 2010

**Comment by katiechan** [comment]
The argument for Assessments' "com-nom" parameter should not have "File:" in it.
