### ISSUE TITLE
Should closes FPX/FPD nominations

### ISSUE THREAD

**Issue by katiechan** [Zitrax/FPCBot#7]
Does not currently archive FPX/FPD nominations

**Comment by eatcha-wikimedia** [comment]
FPX done, now let's fix FPD

**Comment by eatcha-wikimedia** [comment]
SEE 
https://commons.wikimedia.org/w/index.php?title=Commons:Featured_picture_candidates/candidate_list&diff=prev&oldid=352156817

https://commons.wikimedia.org/w/index.php?title=Commons:Featured_picture_candidates/candidate_list&diff=prev&oldid=352115917

https://commons.wikimedia.org/w/index.php?title=Commons:Featured_picture_candidates/candidate_list&diff=prev&oldid=352061621
